/****** Object:  StoredProcedure [dbo].[Create_Changelog]    Script Date: 7/13/2022 1:43:53 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[Create_Changelog]  
(  
    -- Add the parameters for the stored procedure here  
 @CHANGED_BY_ID [nvarchar](250),  
    @CHANGED_BY_EMAIL [nvarchar](250),  
    @PLANT_ID [nvarchar](250),  
 @ERP [nvarchar](250),  
 @MRPArea [nvarchar](250),  
    @MATERIAL_ID [nvarchar](250),  
 @SERVICE_LEVEL_NEW [nvarchar](4),  
 @ROP_OLD [nvarchar](30),  
 @ROP_NEW [nvarchar](30),  
 @MAX_OLD [nvarchar](30),  
 @MAX_NEW [nvarchar](30),  
 @MLS_OLD [nvarchar](30),  
 @MLS_NEW [nvarchar](30),  
 @ROUNDING_VALUE_NEW int,  
 @ROUNDING_VALUE_OLD int,  
 @BASE_UNIT_OF_MEASURE [nvarchar](30),  
 @MI decimal(30,3),  
 @MI_IND [nvarchar](30),  
 @CURRENCY_CD [nvarchar](10),  
 @UNRISTRICRTED_STOCK_QUANTITY bigint,  
 @UNIT_COST decimal(30,3),  
 @COMMENT [nvarchar](200)  
)  
AS  
BEGIN
--TRANS_TYPE
IF (@ROP_NEW IS NOT NULL AND @ROP_NEW > 0)
INSERT INTO [ui].[CHANGE_LOG] ([USER_ID], [USER_EMAIL], [LAST_CHANGED], [PLANT_FACILITY_SAP_ID], [MATERIAL_TYPE_SAP_ID], [ERP_CD], [MRP_AREA_SAP_ID], [SERVICE_LEVEL], [ROP_OLD], [ROP_NEW], [MAX_OLD], [MAX_NEW], [MLS_OLD], [MLS_NEW], [ROUNDING_VALUE_NEW], [ROUNDING_VALUE_OLD], [BASE_UNIT_OF_MEASURE_SAP_ID], [MONETARY_IMPACT], [IMPACT_TYPE_IND], [CURRENCY_CD], [UNIT_COST_AMT], [EDAM_VALUATED_UNRESTRICTED_USE_STOCK_QTY], [COMMENT], [TRANS_TYPE] ) 
VALUES (@CHANGED_BY_ID, @CHANGED_BY_EMAIL, GETDATE(), @PLANT_ID , @MATERIAL_ID , @ERP , @MRPArea , @SERVICE_LEVEL_NEW , @ROP_OLD, @ROP_NEW , NULL, NULL , NULL, NULL, NULL, NULL, @BASE_UNIT_OF_MEASURE, @MI, @MI_IND, @CURRENCY_CD, @UNIT_COST, @UNRISTRICRTED_STOCK_QUANTITY, @COMMENT, 'ROP' ) 

IF (@MAX_NEW IS NOT NULL AND @MAX_NEW > 0)
INSERT INTO [ui].[CHANGE_LOG] ([USER_ID], [USER_EMAIL], [LAST_CHANGED], [PLANT_FACILITY_SAP_ID], [MATERIAL_TYPE_SAP_ID], [ERP_CD], [MRP_AREA_SAP_ID], [SERVICE_LEVEL], [ROP_OLD], [ROP_NEW], [MAX_OLD], [MAX_NEW], [MLS_OLD], [MLS_NEW], [ROUNDING_VALUE_NEW], [ROUNDING_VALUE_OLD], [BASE_UNIT_OF_MEASURE_SAP_ID], [MONETARY_IMPACT], [IMPACT_TYPE_IND], [CURRENCY_CD], [UNIT_COST_AMT], [EDAM_VALUATED_UNRESTRICTED_USE_STOCK_QTY], [COMMENT], [TRANS_TYPE] ) 
VALUES (@CHANGED_BY_ID, @CHANGED_BY_EMAIL, GETDATE(), @PLANT_ID , @MATERIAL_ID , @ERP , @MRPArea , @SERVICE_LEVEL_NEW , NULL, NULL , @MAX_OLD, @MAX_NEW , NULL, NULL, NULL, NULL, @BASE_UNIT_OF_MEASURE, @MI, @MI_IND, @CURRENCY_CD, @UNIT_COST, @UNRISTRICRTED_STOCK_QUANTITY, @COMMENT, 'MAX' ) 

IF (@MLS_NEW IS NOT NULL AND @MLS_NEW > 0)
INSERT INTO [ui].[CHANGE_LOG] ([USER_ID], [USER_EMAIL], [LAST_CHANGED], [PLANT_FACILITY_SAP_ID], [MATERIAL_TYPE_SAP_ID], [ERP_CD], [MRP_AREA_SAP_ID], [SERVICE_LEVEL], [ROP_OLD], [ROP_NEW], [MAX_OLD], [MAX_NEW], [MLS_OLD], [MLS_NEW], [ROUNDING_VALUE_NEW], [ROUNDING_VALUE_OLD], [BASE_UNIT_OF_MEASURE_SAP_ID], [MONETARY_IMPACT], [IMPACT_TYPE_IND], [CURRENCY_CD], [UNIT_COST_AMT], [EDAM_VALUATED_UNRESTRICTED_USE_STOCK_QTY], [COMMENT], [TRANS_TYPE] ) 
VALUES (@CHANGED_BY_ID, @CHANGED_BY_EMAIL, GETDATE(), @PLANT_ID , @MATERIAL_ID , @ERP , @MRPArea , @SERVICE_LEVEL_NEW , NULL, NULL , NULL, NULL , @MLS_OLD, @MLS_NEW, NULL, NULL, @BASE_UNIT_OF_MEASURE, @MI, @MI_IND, @CURRENCY_CD, @UNIT_COST, @UNRISTRICRTED_STOCK_QUANTITY, @COMMENT, 'MLS' ) 
 
IF (@ROUNDING_VALUE_NEW IS NOT NULL AND @ROUNDING_VALUE_NEW > 0)
INSERT INTO [ui].[CHANGE_LOG] ([USER_ID], [USER_EMAIL], [LAST_CHANGED], [PLANT_FACILITY_SAP_ID], [MATERIAL_TYPE_SAP_ID], [ERP_CD], [MRP_AREA_SAP_ID], [SERVICE_LEVEL], [ROP_OLD], [ROP_NEW], [MAX_OLD], [MAX_NEW], [MLS_OLD], [MLS_NEW], [ROUNDING_VALUE_NEW], [ROUNDING_VALUE_OLD], [BASE_UNIT_OF_MEASURE_SAP_ID], [MONETARY_IMPACT], [IMPACT_TYPE_IND], [CURRENCY_CD], [UNIT_COST_AMT], [EDAM_VALUATED_UNRESTRICTED_USE_STOCK_QTY], [COMMENT], [TRANS_TYPE] ) 
VALUES (@CHANGED_BY_ID, @CHANGED_BY_EMAIL, GETDATE(), @PLANT_ID , @MATERIAL_ID , @ERP , @MRPArea , @SERVICE_LEVEL_NEW , NULL, NULL , NULL, NULL , NULL, NULL, @ROUNDING_VALUE_NEW, @ROUNDING_VALUE_OLD, @BASE_UNIT_OF_MEASURE, @MI, @MI_IND, @CURRENCY_CD, @UNIT_COST, @UNRISTRICRTED_STOCK_QUANTITY, @COMMENT, 'RND' ) 
  
 UPDATE [ui].[CA_R_UI_ACTIVE_RECOMMENDATION_GRA_001]  
 set REVIEW_DATE = GETDATE(),  
  REVIEWED_BY = @CHANGED_BY_ID  
 where [ERP_CD] = @ERP AND  
    [PLANT_FACILITY_SAP_ID] = @PLANT_ID AND  
    [MRP_AREA_SAP_ID] = @MRPArea AND  
    [MATERIAL_TYPE_SAP_ID] = @MATERIAL_ID  
  
 UPDATE [ui].[CA_R_UI_REVIEW_POSTPONED]  
 set REVIEW_DATE = GETDATE(),  
  REVIEWED_BY = @CHANGED_BY_ID  
 where [PLANT_FACILITY_SAP_ID] = @PLANT_ID AND  
    [MATERIAL_TYPE_SAP_ID] = @MATERIAL_ID AND  
    [ERP_CD] = @ERP AND  
    [MRP_AREA_SAP_ID] = @MRPArea  
  
END  
